apiVersion: apps/v1
kind: Deployment
metadata:
  name: tessera-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tessera-1
  template:
    metadata:
      labels:
       io.kompose.service: tessera-1
    spec:
      containers:
      - name: tessera-1
        image: pharosproduction/tessera:0.8.4v2
        command:
          - tessera
          # - /bin/bash
        tty: true
        resources:
        volumeMounts:
        - mountPath: /opt/tessera/qdata
          name: tessera-1-claim0
        workingDir: /opt/tessera
      volumes:
      - name: tessera-1-claim0
        hostPath:
          # directory location on host
          path: /Users/lesha/privori-quorum-k8s/Docker-cluster/node-1/tessera/qdata
          type: Directory
      # imagePullSecrets:
      #   - name: regcred



